name: Generate Snake Animation

on:
  schedule:
    - cron: "0 12 * * *" # 每天 12:00 UTC 运行
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    # Add permissions explicitly
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # 添加调试步骤
      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          dark_mode_svg_out_path: dist/github-contribution-grid-snake-dark.svg

      # 添加调试步骤
      - name: List directory contents
        run: ls -la dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
